INSERT INTO public.adaptability_questions (text, "order") VALUES
('Si ce que quelqu''un vous dit est erroné, avez-vous tendance à intervenir immédiatement ?', 1),
('Avez-vous l''habitude de demander à votre interlocuteur de préciser sa pensée, si vous estimez ne pas l''avoir comprise ?', 2),
('Avez-vous tendance à parler de plusieurs choses à la fois, à ouvrir beaucoup de parenthèses ?', 3),
('Vous est-il difficile d''être en désaccord avec quelqu''un que vous appréciez beaucoup ?', 4),
('Quand un sujet vous passionne, avez-vous tendance à monopoliser la parole ?', 5),
('Avez-vous tendance à dire toujours ce que vous pensez, quoi qu''il arrive ?', 6),
('Vous reproche-t-on souvent de vouloir avoir toujours raison ?', 7),
('Avez-vous la réputation d''être long dans vos explications ?', 8),
('Dans le cadre professionnel, face à un inconnu, faites-vous toujours l''effort de vous exprimer avec des termes courants ?', 9),
('A la fin d''un entretien, avez-vous tendance à demander à votre interlocuteur comment il a vécu l''échange ?', 10),
('Quand vous téléphonez, avez-vous l''habitude d''articuler et de parler moins vite ?', 11),
('Quand un collègue vous fait une critique, avez-vous tendance à vouloir le convaincre à tout prix qu''il se trompe ?', 12),
('Si une personne vous a heurté, avez-vous tendance à lui en parler sans délai ?', 13),
('Lorsque vous échangez avec les autres, pensez-vous aux réactions qu''ils peuvent avoir à ce que vous allez leur dire ?', 14),
('Vous arrive-t-il de faire semblant de vous intéresser à ce qu''on vous dit ?', 15),
('Avez-vous tendance à parler facilement de sujets très personnels ?', 16),
('Etes-vous du genre à reconnaître spontanément vos torts si vous avez commis une erreur ?', 17),
('Etes-vous d''humeur égale ?', 18),
('Aimez-vous faire des sous-entendus quand vous parlez ?', 19),
('Acceptez-vous les compliments ?', 20); 